name: yu_events
description: "A new Flutter project."
publish_to: "none" # Prevents accidental publication to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.1

dependencies:
  flutter:
    sdk: flutter
  google_maps_flutter: ^2.3.0
  cloud_firestore: ^4.10.2
  firebase_core: ^2.32.0
  firebase_auth: ^4.8.1
  url_launcher: ^6.1.7
  geolocator: ^9.0.2
  cupertino_icons: ^1.0.8
  js: ^0.7.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  # Add assets here
  assets:
    - assets/images/
